spring.profiles.active=local
spring.sql.init.mode=always

#Scheduler run interval (default=30 minutes)
checker.interval-ms=1800000

#email settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.username=
spring.mail.password=