spring.sql.init.mode=always

#Scheduler run interval (default=30 minutes)
checker.interval-ms=1800000

#Email notification cooldown (default=1 week)
cooldown.interval-ms=604800000

#Checker config file location
app.checkers-file=/config/checkers.json

# HTTP client settings
spring.http.client.connect-timeout=10s
spring.http.client.read-timeout=10s


#email settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
app.notifier.recipient=${NOTIFIER_RECIPIENT}

#database settings
spring.datasource.url=jdbc:postgresql://db:5432/stocktracker
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#redis settings
spring.data.redis.host=redis