CREATE TABLE COOLDOWN
(
    id        BIGSERIAL PRIMARY KEY,
    url       VARCHAR(2048) NOT NULL UNIQUE,
    last_seen TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    disabled  BOOLEAN       NOT NULL DEFAULT FALSE
);